name: thesisapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  camera_android: ^0.10.9+2
  camera_web: 0.3.3
  image_picker: ^1.1.1
  image_picker_android: ^0.8.12 
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  readmore: ^3.0.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/model/detect.tflite
    - assets/model/labelmap.pbtxt
    - assets/model/labelmap.txt
  fonts:
    - family: Inknut Antiqua
      fonts:
        - asset: assets/fonts/InknutAntiquaMedium.ttf
          weight: 500
        - asset: assets/fonts/InknutAntiquaLight.ttf
          weight: 300
        - asset: assets/fonts/InknutAntiquaRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBlack.ttf
          weight: 900
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: KoHo
      fonts:
        - asset: assets/fonts/KoHoBold.ttf
          weight: 700
        - asset: assets/fonts/KoHoMedium.ttf
          weight: 500
        - asset: assets/fonts/KoHoSemiBold.ttf
          weight: 600
    - family: Imprima
      fonts:
        - asset: assets/fonts/ImprimaRegular.ttf
          weight: 400
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/InconsolataSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InconsolataMedium.ttf
          weight: 500
    - family: Inria Sans
      fonts:
        - asset: assets/fonts/InriaSansLight.ttf
          weight: 300
    - family: Karla
      fonts:
        - asset: assets/fonts/KarlaMedium.ttf
          weight: 500
        - asset: assets/fonts/KarlaBold.ttf
          weight: 700
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSansRomanLight.ttf
          weight: 300
